# Generated by Django 4.0.3 on 2022-04-07 20:37

import bookstore_app.common.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_age_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[bookstore_app.common.validators.MinDateValidator(datetime.date(1920, 1, 1)), bookstore_app.common.validators.MaxDateValidator(datetime.date(2022, 4, 7))]),
        ),
    ]
