# Generated by Django 4.0.3 on 2022-04-10 11:26

import bookstore_app.common.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_age_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[bookstore_app.common.validators.MinDateValidator(datetime.date(1920, 1, 1)), bookstore_app.common.validators.MaxDateValidator(datetime.date(2022, 4, 10))]),
        ),
    ]
