# Generated by Django 4.0.3 on 2022-03-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_book_comment_comment_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
