# Generated by Django 4.0.3 on 2022-03-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
